### ISSUE TITLE
Add Logcollector Module to Wazuh Agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#201]
## Description

Logcollector is the agent module that adds the ability to collect system logs, both by reading plain text files and by collecting messages from the operating system API.

This task consists of redesigning the Logcollector module of the 4.x agent and implementing it in the new agent.

## Functional Requirements

- **Implement collectors** for:
    - Plaintext logs
    - macOS (using ULS) - macOS only
    - journald - Linux only
    - Windows (using eventchannel) - Windows only
- **Detect changes** including:
    - Wildcard matches for log file names
    - Rotated log files
    - Truncated log files
- **Store persistent state** for:
    - Reading position of each log file
    - Last modification date of each file
    - On start, reload state and act accordingly
- **Transmit logs** as stateless messages

## Non-functional Requirements

- A default configuration must be provided in the code.
- A proposal for configuration settings should be defined.

## Implementation Constraints

- Logcollector should be implemented as a module rather than a standalone executable.

## Deliverables

1. Wazuh Agent executable with the Logcollector module included
2. Design documentation for the module
3. Configuration documentation

**Comment by vikman90** [comment]
## Design

### Class Diagram

```mermaid
---
title: Logcollector 5.0
---
classDiagram
    class ModuleWrapper
    class Logcollector {
        - maxLogSize : int
        + start()
        + setup(ConfigurationParser)
        + stop()
        + executeCommand(CommandResult(string))
        + name() : string
        + getMaxLogSize() : int
    }
    class IReader {
        + run()
    }
    class FileReader {
        - queue : Queue
        - store : Store
        - fileGlob : string
        - age : int
        - delimRegex : string
        - useBookmark : bool
        + FileReader(queue, store, fileGlob, age, delimRegex, useBookmark)
        + run()
        - reload()
    }
    class LocalFile {
        + Localfile(path)
        + path : string
        + offset : int
        + inode : int
    }
    class JournaldReader {
        - queue : Queue
        - store : Store
        - useBookmark : bool
        + JournalReader(queue, store, useBookmark)
        + addFilter(filter)
        + run()
    }
    class JournaldFilter {
        + field : string
        + query : string
        + ignoreMissing : bool
    }
    class WindowsEventReader {
        - queue : Queue
        - store : Store
        - channel : string
        - query : string
        - useBookmark : bool
        - reconnectTime : int
        + WindowsEventReader(queue, store, channel, query, useBookmark, reconnectTime)
        + run()
        - reconnect()
    }
    class AppleReader {
        - queue : Queue
        - store : Store
        - query : string
        - useBookmark : bool
        + AppleReader(queue, store, query, useBookmark)
        + run()
    }
    ModuleWrapper <-- Logcollector
    Logcollector o-- IReader
    IReader <|-- FileReader
    IReader <|-- JournaldReader
    IReader <|-- WindowsEventReader
    IReader <|-- AppleReader
    FileReader o-- LocalFile
    JournaldReader o-- JournaldFilter
```

## Configuration

### Sample

```yaml
logcollector:
  - type: file
    location: /var/log/*.log
    age: 1d
    delimRegex: "\n"
    useBookmark: true
  - type: windows
    channel: Application
    query: Event[System/EventID = 4624]
    useBookmark: true
    reconnectTime: 5m
  - type: journald
    filter:
      - field: "_SYSTEMD_UNIT"
        query: ^ssh.service$
      - field: PRIORITY
        query: "[0-3]"
        ignore-missing: true
    useBookmark: true
  - type: macos
    query:
    useBookmark: true
```
