### ISSUE TITLE
Standardize Time Unit in Agent Configuration Parser

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#286]
**Parent Issue:** https://github.com/wazuh/wazuh-agent/issues/241

## Description

Currently, the agent's configuration includes time-based options, each specified with implicit or explicit time units. For example:

```yaml
agent:
  retry_interval_secs: 30
inventory:
  interval: 3600
logcollector:
  reload_interval: 60
  file_wait: 500
```

Here:
- `retry_interval_secs` explicitly indicates seconds with the `_secs` suffix.
- `interval`, `reload_interval` and `file_wait` assume seconds but do not specify a unit.

To improve consistency and user experience, I propose the following changes:

1. **Adopt Seconds as the Default Time Unit**  
   All time-based options will default to seconds, making seconds the standard across the configuration.
   
2. **Rename `retry_interval_secs` to `retry_interval`**  
   By removing the `_secs` suffix, we align with the naming convention of other time-based options, reinforcing the default unit as seconds.

3. **Implement Support for Standard Time Suffixes**  
   Add support for standard time suffixes to improve flexibility and readability. This enhancement will allow users to specify units directly, supporting:
   - **`ms` for milliseconds**
   - **`s` for seconds**
   - **`m` for minutes**
   - **`h` for hours**
   - **`d` for days**

   For instance:
   ```yaml
   agent:
     retry_interval: 30s
   inventory:
     interval: 1h
   logcollector:
     reload_interval: 1m
     file_wait: 500ms
   ```

This change will enhance readability and maintain consistency across the configuration.
