### ISSUE TITLE
Update Inventory Module for Common Schema Compliance

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#292]
**Parent Issue:** #253

## Description

Update the inventory module to adhere to the common schema for enhanced consistency and compatibility.

We should consider applying a new mapping phase in the output of DBsync, before pushing messages into the Queue:

```mermaid
flowchart TD
    subgraph Inventory
    A(DataProvider) --> |JSON| B(DBsync)
    B <-->|Mapping| D@{shape: cyl, label: "SQLite"}
    B --> F(Mapping)
    style F color:red
    end
    subgraph Agent
    F --> C(Queue)
    C --> E(Communicator)
    end
```

## Subtasks

- #296
- #293
- #295
- #297
- #298
- #299
- #284
- #294

## References

- Common schema definitions: [Wazuh Indexer Plugins](https://github.com/wazuh/wazuh-indexer-plugins/tree/master/plugins/setup/src/main/resources)
- ECS documentation: [Elastic ECS Documentation](https://www.elastic.co/guide/en/ecs/current/index.html)

**Comment by cborla** [comment]
## Updated inventory configuration fields. `wazuh-agent.yml`
``` yml
inventory:
  enabled: false
  interval: 1h
  scan_on_start: true
  hardware: true
  system: true
  networks: true
  packages: true
  ports: true
  ports_all: true
  processes: true
  hotfixes: true
```
