### ISSUE TITLE
Make Event Batching Configurable

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#306]
**Parent Issue:** #241

## Description

Currently, the Wazuh Agent sends batches of messages from its queue to the server every second. We propose making the batching process configurable to allow greater flexibility.

The agent should send a batch of messages under the first condition that occurs:
1. If `batch_interval` has elapsed since the last batch and there are messages in the queue.
2. If the accumulated size of messages in the queue reaches `batch_size`.

This design ensures:  
- Messages do not stay in the queue for longer than `batch_interval` seconds.  
- Requests do not exceed a specified maximum size.  
- The queue drains at a controlled rate, preventing overflow unless external limitations apply.  

## Proposed Configuration Options

The following parameters can be added to `agent.yml`:

```yml
events:
  batch_interval: "10s"  # Maximum time between batch sends (default: 10 seconds).
  batch_size: "1000"       # Maximum number of messages in a batch (default: 1000).
```

### Parameter Details

- **`batch_interval`**:
  - Specifies the maximum time between batch sends.
  - Accepts values with time units: `"500ms"`, `"10s"`, `"1m"`, `"1h"`.
  - Valid range: `"1s"` to `"1h"`.

- **`batch_size`**:
  - Specifies the maximum number of messages in a batch.
  - Valid range: `"1000"` to `"1000000"`.
