### ISSUE TITLE
Modify Registration URL Definition

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#317]
**Parent Issue:** #241

## Description
The agent has two primary connections:
1. Registration
2. Server connection for event reporting and command queries.

Currently, these are defined in `wazuh-agent.yml` as:
```yml
agent:
  server_url: https://localhost:27000
  registration_url: https://localhost:55000
```

## Proposal
Since registration is a one-time, on-demand operation initiated via CLI, we propose:
1. Removing the `registration_url` configuration option.
2. Introducing a new CLI parameter `--url` for registration operations.

### Example Command
```bash
./wazuh-agent --config-file wazuh-agent.yml --register-agent --user wazuh --password topsecret --name dummy --url https://localhost:55000
```
