### ISSUE TITLE
Testing E2E mvp agent 

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#403]
## Description
The objective of this issue is to perform a start-to-finish test, in which we can verify the correct functionallity of the agent.
Points to verify.

- Agent registration.
- Agent stateful events.
  - System
  - Hardware
  - Porcesses
  - Packagess
  - Ports
  - Networks
- Stateless Events

## DoD
- Leave evidence of each test, and how it was executed.

**Comment by TomasTurina** [comment]
## Installation (server side)

The following vagrant environment was used:

[5.zip](https://github.com/user-attachments/files/18067291/5.zip)

### Dashboard

![image](https://github.com/user-attachments/assets/62cdd281-ed2c-4bee-8c92-6e41962e778e)

### Indexer

![image](https://github.com/user-attachments/assets/72c9a6fd-a6d5-4a7f-b2c0-338927a1424c)

### Server

![image](https://github.com/user-attachments/assets/4714bc0c-a337-42fd-8887-fdbb85f2cf0e)

#### Configuration:

```
server:
  nodes:
   - master
  node:
    name: manager_01
    type: master
    ssl:
      key:  "/etc/wazuh-server/server.key"
      cert: "/etc/wazuh-server/server.cert"
      ca:  "/etc/wazuh-server/server.ca"
management_api:
  host:
    - "0.0.0.0"
    - "::"
communications_api:
  host: "0.0.0.0"
indexer:
    hosts:
      - host: "127.0.0.1"
        port: 9200
    username: "admin"
    password: "admin"
    ssl:
      use_ssl: true
      key: "/etc/wazuh-indexer/certs/admin-key.pem"
      certificate: "/etc/wazuh-indexer/certs/admin.pem"
      certificate_authorities:
        - "/etc/wazuh-server/server.ca"
```
