### ISSUE TITLE
Conditional rules

### ISSUE THREAD

**Issue by DijkstraSolutions** [wazuh/wazuh-agent#548]
|4.10.1|agent|deb|apt install|ubuntu 24.04.01|

SCA rules need to have nested conditional rules, for example:

If you have nftables only installed, this shows as a fail:

```
  # 3.5.3.1.2 Ensure nftables is not installed with iptables. (Automated)
  - id: 28584
    title: "Ensure nftables is not installed with iptables."
    description: "nftables is a subsystem of the Linux kernel providing filtering and classification of network packets/datagrams/frames and is the successor to iptables."
    rationale: "Running both iptables and nftables may lead to conflict."
    remediation: "Run the following command to remove nftables: # apt purge nftables."
    compliance:
      - cis: ["3.5.3.1.2"]
      - cis_csc_v8: ["4.4", "4.5"]
      - cis_csc_v7: ["9.4"]
      - cmmc_v2.0: ["AC.L1-3.1.20", "CM.L2-3.4.7", "SC.L1-3.13.1", "SC.L2-3.13.6"]
      - iso_27001-2013: ["A.13.1.1"]
      - mitre_tactics: ["TA0011"]
      - mitre_techniques: ["T1562", "T1562.004"]
      - nist_sp_800-53: ["SC-7(5)"]
      - pci_dss_v3.2.1: ["1.1.4", "1.3.1", "1.4"]
      - pci_dss_v4.0: ["1.2.1", "1.4.1"]
      - soc_2: ["CC6.6"]
    condition: all
    rules:
      - "c:dpkg-query -s iptables -> r:install ok installed"
      - "not c:dpkg-query -s nftables -> r:install ok installed"
```

what is needed is something like this:

```
    condition: any
    rules:
      - condition: all  # iptables not installed, nftables installed
        rules:
          - "not c:dpkg-query -s iptables -> r:^Status: install ok installed"  # Not installed
          - "c:dpkg-query -s nftables -> r:^Status: install ok installed"  # Installed
      - condition: all  # nftables not installed, iptables installed
        rules:
          - "not c:dpkg-query -s nftables -> r:^Status: install ok installed"  # Not installed
          - "c:dpkg-query -s iptables -> r:^Status: install ok installed"  # Installed
```

This currently doesn't work, as it was tested with 4.10.1 on ubuntu 24.04.01, other versions/environments not tested.
