### ISSUE TITLE
SCA: Implement Configuration Parsing

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#681]
## Description
This task focuses on implementing the configuration parsing functionality for the SCA module. The module must be able to read, validate, and apply configuration settings from YAML format.

Example configuration:

```
sca:
  enabled: true
  scan_on_start: true
  interval: 1h
  policies:
    - etc/shared/cis_debian10.yml
    - /my/custom/policy/path/my_policy.yaml
  policies_disabled:
    - ruleset/sca/cis_debian9.yml
```

## Tasks
1. **Research & Design**
   - Define required configuration parameters and default values.
   - Establish validation rules and error handling mechanisms.

2. **Development**
   - Integrate configuration handling within the module’s initialization process.
   - Ensure proper validation and error reporting mechanisms.

3. **Unit Testing**
   - Develop test cases covering valid and invalid configurations.
   - Ensure robust error handling and fallback mechanisms.
   - Verify correct application of configuration parameters in runtime scenarios.

4. **Documentation**
   - Document supported configuration options, formats, and examples.

## Definition of Done
- [ ] Configuration parameters, formats, and validation rules are defined.
- [ ] Configuration parser is implemented with validation and error handling.
- [ ] Unit tests cover parsing logic and error scenarios.
- [ ] Documentation is complete and reviewed.
