### ISSUE TITLE
Define a default configuration per platform

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#694]
The installer provides a default configuration file, _wazuh-agent.yml_. This file contains numerous settings but is specifically tailored for Linux.

The final version of the agent will likely have a minimal configuration. The manager will transmit a more complete configuration, adapted to its platform and configuration group.

However, to facilitate testing, we should provide a default configuration file that is more suitable for each platform (Linux, Windows, and macOS), allowing the agent to be tested without requiring any configuration.

## Tasks

- Split the configuration into three files:
   - wazuh_agent_linux.yml
   - wazuh_agent_windows.yml
   - wazuh_agent_macos.yml
- Propose a suitable default configuration for each platform.
- Adapt the installer to copy the appropriate configuration file for the platform.

## Acceptance Criteria

- The installer copies the appropriate configuration file for the platform.

**Comment by LucioDonda** [comment]
## Specific configurations proposal

* Linux 
Renamed and hotfixes set to false

```yaml
agent:
  thread_count: 4
  server_url: https://localhost:27000
  retry_interval: 30s
  verification_mode: none
  queue_size: 10000
events:
  batch_interval: 10s
  batch_size: 1MB
inventory:
  enabled: true
  interval: 1h
  scan_on_start: true
  hardware: true
  system: true
  networks: true
  packages: true
  ports: true
  ports_all: false
  processes: false
  hotfixes: false
logcollector:
  enabled: true
  localfiles:
    - /var/log/auth.log
  reload_interval: 1m
  read_interval: 500ms

```

* Macos 
Added specific logcollector (taken from the Readme)

```yaml
agent:
  thread_count: 4
  server_url: https://localhost:27000
  retry_interval: 30s
  verification_mode: none
  queue_size: 10000
events:
  batch_interval: 10s
  batch_size: 1MB
inventory:
  enabled: true
  interval: 1h
  scan_on_start: true
  hardware: true
  system: true
  networks: true
  packages: true
  ports: true
  ports_all: false
  processes: false
  hotfixes: false
logcollector:
  enabled: true
  reload_interval: 1m
  read_interval: 500ms
  localfiles:
    - /var/log/auth.log
  macos:
    - query: process == "sshd" OR message CONTAINS "invalid"
      level: info
      type: trace,activity,log

```

* Windows
Windows event channels taken from 4.x config and hotfixes set to true.

```yaml
agent:
  thread_count: 4
  server_url: https://localhost:27000
  retry_interval: 30s
  verification_mode: none
  queue_size: 10000
events:
  batch_interval: 10s
  batch_size: 1MB
inventory:
  enabled: true
  interval: 1h
  scan_on_start: true
  hardware: true
  system: true
  networks: true
  packages: true
  ports: true
  ports_all: false
  processes: false
  hotfixes: true
logcollector:
  enabled: true
  reload_interval: 1m
  read_interval: 500ms
  windows:
    - channel: Application
      query: "*"
    - channel: Security
      query: Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]
    - channel: System
      query: "*"

```
