### ISSUE TITLE
Process Rule Coverage (Linux, Windows, macOS)

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#767]
**Description**  

Verify the correctness of SCA `check_process` rules — covering both presence and absence of processes on supported platforms.

**Tasks**

- Implement rules like:
  - **Process running**
    - `p:sshd` (Linux/macOS)
    - `p:explorer.exe` (Windows)
  - **Process not running**
    - `not p:netcat`
    - `not p:malware.exe`

**Definition of Done**

- Process name detection is accurate across platforms
- False positives/negatives are addressed
- Unit tests written for process detection logic
- All bugs fixed and verified
- CI tests include active and inactive process validation on all OSes

**Comment by aritosteles** [comment]
# Update

- 2024-05-06: Getting up to speed with latest sca development. Setting up environment. Running first policy tests.

**Comment by aritosteles** [comment]
# Results and evidence

<details><summary> Passed test for process not running</summary>
YAML:

```
sudo cat /etc/wazuh-agent/sca/process.yml 
policy:
  id: "process test policy"
  file: "process.yml"
  name: "Process Test Policy"
  description: "Process Test Policy"
  references:
    - https://www.wazuh.com/

requirements:
  title: "Check Ubuntu version."
  description: "Requirements for running the SCA scan against Ubuntu Linux 24.04 LTS"
  condition: all
  rules:
    - "f:/etc/os-release -> r:Ubuntu 24.04"

checks:
  - id: 02
    title: "Process Test Check"
    description: "Process Test Check"
    rationale: ""
    impact: ""
    remediation: ""
    references:
      - "https://www.wazuh.com/"
    condition: all
    rules:
      - not p:sshd

```

Logs:

```
17:03:27 INFO  s./opt/imposter/config/stateful - 
{"agent":{"groups":[],"host":{"architecture":"x86_64","hostname":"ariel-work-asus","ip":["172.17.0.1","fe80::42:fbff:fe17:5d13","fe80::7c69:37ff:fed4:db5a","192.168.0.147","fe80::c10b:30ee:370a:6995"],"os":{"name":"Ubuntu","type":"Linux","version":"24.04.2 LTS (Noble Numbat)"}},"id":"60e4db05-30f5-41bc-9a22-d2f4d6d38283","name":"dummy","type":"Endpoint","version":"v5.0.0"}}
{"id":"3085d3554a39cac3369e5d1cb40436fc4f61b099","module":"sca","operation":"create"}
{"check":{"condition":"all","description":"Process Test Check","id":"02","impact":"","rationale":"","references":"https://www.wazuh.com/","remediation":"","result":"Not run","rules":["not p:sshd"],"title":"Process Test Check"},"policy":{"description":"Process Test Policy","file":"process.yml","id":"process test policy","name":"Process Test Policy","references":"https://www.wazuh.com/"},"timestamp":"2025-05-07T17:03:17.163Z"}
{"id":"3085d3554a39cac3369e5d1cb40436fc4f61b099","module":"sca","operation":"update"}
{"check":{"condition":"all","description":"Process Test Check","id":"02","rationale":"","remediation":"","result":"Passed","rules":["not p:sshd"]},"policy":{"description":"Process Test Policy","file":"process.yml","id"
```
</details>

<details><summary> Failed test for process not running</summary>
YAML:

```
sudo cat /etc/wazuh-agent/sca/process.yml 
policy:
  id: "process test policy"
  file: "process.yml"
  name: "Process Test Policy"
  description: "Process Test Policy"
  references:
    - https://www.wazuh.com/

requirements:
  title: "Check Ubuntu version."
  description: "Requirements for running the SCA scan against Ubuntu Linux 24.04 LTS"
  condition: all
  rules:
    - "f:/etc/os-release -> r:Ubuntu 24.04"

checks:
  - id: 02
    title: "Process Test Check"
    description: "Process Test Check"
    rationale: ""
    impact: ""
    remediation: ""
    references:
      - "https://www.wazuh.com/"
    condition: all
    rules:
      - p:sshd

```

Logs:

```
17:00:38 INFO  s./opt/imposter/config/stateful - 
{"agent":{"groups":[],"host":{"architecture":"x86_64","hostname":"ariel-work-asus","ip":["172.17.0.1","fe80::42:fbff:fe17:5d13","fe80::7c69:37ff:fed4:db5a","192.168.0.147","fe80::c10b:30ee:370a:6995"],"os":{"name":"Ubuntu","type":"Linux","version":"24.04.2 LTS (Noble Numbat)"}},"id":"60e4db05-30f5-41bc-9a22-d2f4d6d38283","name":"dummy","type":"Endpoint","version":"v5.0.0"}}
{"id":"3085d3554a39cac3369e5d1cb40436fc4f61b099","module":"sca","operation":"create"}
{"check":{"condition":"all","description":"Process Test Check","id":"02","impact":"","rationale":"","references":"https://www.wazuh.com/","remediation":"","result":"Not run","rules":["p:sshd"],"title":"Process Test Check"},"policy":{"description":"Process Test Policy","file":"process.yml","id":"process test policy","name":"Process Test Policy","references":"https://www.wazuh.com/"},"timestamp":"2025-05-07T17:00:28.529Z"}
{"id":"3085d3554a39cac3369e5d1cb40436fc4f61b099","module":"sca","operation":"update"}
{"check":{"condition":"all","description":"Process Test Check","id":"02","rationale":"","remediation":"","result":"Failed","rules":["p:sshd"]},"policy":{"description":"Process Test Policy","file":"process.yml","id":"process test policy","name":"Process Test Policy"},"timestamp":"2025-05-07T17:00:28.554Z"}

```
</details>
