### ISSUE TITLE
Windows Registry Rule Validation (Windows only)

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#768]
**Description**  

Test Windows Registry checks including key existence, key-value existence, and value content validation using string and numeric values.

**Tasks**

- Add these registry rules:
  - **Registry exists**
    - `r:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Defender`
  - **Key exists**
    - `r:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows Defender -> DisableAntiSpyware`
  - **Key value content**
    - `r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge -> 0`

**Definition of Done**

- Registry access and key/value parsing works correctly
- String and numeric comparisons evaluate as expected
- All registry rule types have corresponding unit tests
- Bugs found during validation are fixed
- CI verifies registry checks on supported Windows runners

**Comment by aritosteles** [comment]
# Update

- **2024-05-06:** 
Getting up to speed with latest sca development. Setting up environment. Running first policy tests.

**Comment by aritosteles** [comment]
# Results and evidence

<details><summary> Passed test for existing registry key</summary>
YAML:

```
policy:
  id: "Windows registry policy"
  file: "process.yml"
  name: "Windows registry Test Policy"
  description: "Windows Registry Test Policy"
  references:
    - https://www.wazuh.com/
checks:
  - id: 01
    title: "Windows Registry Test Check"
    description: "Windows Registry Test Check"
    rationale: ""
    impact: ""
    remediation: ""
    references:
      - "https://www.wazuh.com/"
    condition: all
    rules:
      - r:HKEY_LOCAL_MACHINE
```

Logs:

```
19:17:58 INFO  s./opt/imposter/config/stateless - 
{"agent":{"groups":["validYaml","invalidYaml"],"host":{"architecture":"x86_64","hostname":"DESKTOP-RA8EP4J","ip":["192.168.0.169","fe80::551c:c018:301b:fc3","127.0.0.1","::1"],"os":{"name":"Microsoft Windows 10 Pro","type":"Windows","version":"10.0.19045.5737"}},"id":"1f80951b-1d7d-4df0-8dd7-7853fcc2d419","name":"dummy","type":"Endpoint","version":"v5.0.0"}}
{"collector":"check","module":"sca"}
{"check":{"condition":"all","description":"Windows Registry Test Check","id":"01","impact":"","name":"Windows Registry Test Check","rationale":"","references":["https://www.wazuh.com/"],"remediation":"","result":"Not run","rules":["r:HKEY_LOCAL_MACHINE"]},"event":{"action":["check-creation"],"category":["configuration"],"changed_fields":[],"created":"2025-05-08T19:17:48.221Z","type":"creation"},"policy":{"description":"Windows Registry Test Policy","file":"process.yml","id":"Windows registry policy","name":"Windows registry Test Policy","references":["https://www.wazuh.com/"]}}
{"collector":"check","module":"sca"}
{"check":{"condition":"all","description":"Windows Registry Test Check","id":"01","name":"Windows Registry Test Check","previous":{"result":"Not run"},"rationale":"","references":["https://www.wazuh.com/"],"remediation":"","result":"Passed","rules":["r:HKEY_LOCAL_MACHINE"]},"event":{"action":["check-change"],"category":["configuration"],"changed_fields":["check.result"],"created":"2025-05-08T19:17:48.228Z","type":"change"},"policy":{"description":"Windows Registry Test Policy","file":"process.yml","id":"Windows registry policy","name":"Windows registry Test Policy","references":["https://www.wazuh.com/"]}}
```
</details>
